name: deploy-container
on:
  push:
    branches:
      - master
defaults:
  run:
    working-directory: container
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID}}
          aws_bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
          source_dir: 'dist'
